
export const COMMITMENT_LEVEL = "confirmed"
export const DEV_RPC = "https://devnet.helius-rpc.com/?api-key=fd74e123-890c-4add-8e0b-3e1d10e668d1"
export const MAIN_RPC = "http://mainnet.helius-rpc.com/?api-key=fd74e123-890c-4add-8e0b-3e1d10e668d1"
export const KEYPAIR = "5cYNBH5XDsbJq8G8RqsESUeK6gMWpMEBZPAVDWFufAGquasLGHKQ9qc9M98Zne1HMmMpssmnnxBTQyL3jf73ZnhX"
export const TOKEN_ADDRESS = "9RBJdXaJ1u7RQtsZ5pHPRLnq1dQXCjibQBtyTArr2B2F"
export const BLOCKENGINE_URL = "BLOCKENGINE_URL=mainnet.block-engine.jito.wtf,ny.mainnet.block-engine.jito.wtf,amsterdam.mainnet.block-engine.jito.wtf,frankfurt.mainnet.block-engine.jito.wtf,tokyo.mainnet.block-engine.jito.wtf"
export const JITO_AUTH_KEYPAIR="2hgM3fr1PF1Yq9TJAhTHq8YSKkCBW96v6AAkmdXxB8xSuDpsZ1vUnE1tsXbRmGxHHLWadjM2yjgAgksgKqX154FB"
export const PINATA_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3JtYXRpb24iOnsiaWQiOiJjM2ExNDQ4ZS1mYjI2LTQzMGMtYjg1NS1kZmNkMzliYzJhYmYiLCJlbWFpbCI6InJldm9pdEBmb3htYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJwaW5fcG9saWN5Ijp7InJlZ2lvbnMiOlt7ImRlc2lyZWRSZXBsaWNhdGlvbkNvdW50IjoxLCJpZCI6IkZSQTEifSx7ImRlc2lyZWRSZXBsaWNhdGlvbkNvdW50IjoxLCJpZCI6Ik5ZQzEifV0sInZlcnNpb24iOjF9LCJtZmFfZW5hYmxlZCI6ZmFsc2UsInN0YXR1cyI6IkFDVElWRSJ9LCJhdXRoZW50aWNhdGlvblR5cGUiOiJzY29wZWRLZXkiLCJzY29wZWRLZXlLZXkiOiJjM2U3OWNlZmEwY2JjYTJhZWUyNyIsInNjb3BlZEtleVNlY3JldCI6ImU2N2Y3MzY4ZmZmNDFjNmU0MjEwNjRiMDhiMDMwMGY2YmIwNmZlYjRkMzM2NjVlMzVkOWJlOGQ1ODNjOTExMmMiLCJleHAiOjE3NjQ5MDA3MTB9.XA9A_58EZvffIe74ghsZHwXLTwL6EKjE6Pfh3R4VuUI"

const COMPUTE_UNIT_PRICE = 1_800_000 

export const ENV = {
    COMPUTE_UNIT_PRICE,
    // JITO_AUTH_KEYPAIR,
    // JITO_BLOCK_ENGINE_URL
}
